### ISSUE TITLE
Erro Pyaes

### ISSUE THREAD

**Issue by victorTrofelli** [guilhermej/scantime_py_crypter#1]
Estou tendo problemas com o PyAES, acredito que seja por eu estar utilizando a versão 3 do python.
Quando vou tentar criptografar o file_name da erro na variavel aes, dizendo que devo utilizar a key em formato bytes e não consigo prosseguir.

obs: Estou utilizando o Python 3.9 pois estou tendo problemas com o pip do python 2.7
![Screenshot_1](https://user-images.githubusercontent.com/49568664/100119261-6d8d3280-2e55-11eb-9421-3361d996f7b7.png)

**Comment by guilhermej** [comment]
Boa tarde Victor, todas as dúvidas devem ser resolvidas de dentro do fórum de dúvidas do curso.

**Comment by victorTrofelli** [comment]
> Boa tarde Victor, todas as dúvidas devem ser resolvidas de dentro do fórum de dúvidas do curso.

Ah, tem algum curso da solyd que tem uma aula sobre esse crypter? Acabei encontrando por acaso o seu github e acabei baixando pois estou estudando o curso de python basico da solyd. Posso tirar essa duvida no curso básico?

**Comment by SirDankenstien** [comment]
whats the fix?
